### ISSUE TITLE
Download Invoice page is showing 500 error

### ISSUE THREAD

**Issue by heykarimoff** [djangocon/2019.djangocon.eu#261]
In Ticket Holder Area, when "Download Invoice" is clicked it is showing 500 error page.
Link to the page: https://members.2019.djangocon.eu/tickets/tickets/

**Comment by benjaoming** [comment]
Thanks a lot for reporting this @heykarimoff 

We made a lot of changes yesterday to accommodate a specific order that had many different ticket types in the same go :) And then we forgot about the oldest problem in Django: `TypeError: 'ManyRelatedManager' object is not iterable` :tada:

**Comment by benjaoming** [comment]
(which happened because we swapped out a reverse relation as in `related_name` with a ManyToManyField.

**Comment by heykarimoff** [comment]
@benjaoming I checked out it's working fine now. Thanks you.👍
