### ISSUE TITLE
Time slots on workshop attendance page are 2hrs before the official schedule

### ISSUE THREAD

**Issue by bartoszgrabski** [djangocon/2019.djangocon.eu#320]
Time slots on https://members.2019.djangocon.eu/ticketholder/workshops/ page are 2 hours before what's in schedule (UTC ?).

Example: Building a Serverless Django Application - Thursday 08:45-09:45
Official schedule and workshop page (https://2019.djangocon.eu/talks/building-a-serverless-django-application/) shows 10:45-11:45

**Comment by benjaoming** [comment]
Thanks! We have been jumping around between UTC and local time for the Django project settings and didn't notice this.

**Comment by benjaoming** [comment]
@rixx do you know the danger of running PreTalx with `TIME_ZONE` not set to `"UTC"`? I recall this was a setting that was recommended not to change?

**Comment by benjaoming** [comment]
Thanks again for reporting this @bartoszgrabski - I can confirm that it's fixed now. AFAIK we don't display dates and times to users anywhere else currently... but would be nice not to repeat the mistake in 2 days, so if we can fix this properly in the Django settings, we'll do that :)

**Comment by rixx** [comment]
@benjaoming pretalx should not be affected by a different `TIME_ZONE` setting, and changing it shouuuld be safe too.

**Comment by benjaoming** [comment]
Super nice, thanks @rixx 

I tried changing it and the schedule and everything remained fine and intact.
