### ISSUE TITLE
Ticketholder section not working

### ISSUE THREAD

**Issue by 153957** [djangocon/2019.djangocon.eu#323]
Whenever we visit ticketholder parts of the site we keep being redirected to the Login form, for example on the https://members.2019.djangocon.eu/ticketholder/sprints/ page.
We do have ticketholder accounts and updated passwords..

**Comment by benjaoming** [comment]
Sorry for this, it's true that you could not view this page, because your ticket was falsely marked as refunded.

There's a weird bug in the data fetched from the API, so we'll use a different key in the output for marking tickets refunded, see: #324

**Comment by benjaoming** [comment]
It's now fixed, thanks so much for reporting!

**Comment by benjaoming** [comment]
Please let us know if you have any further issues!
