### ISSUE TITLE
Ticket widget follow-up issues

### ISSUE THREAD

**Issue by benjaoming** [djangocon/2019.djangocon.eu#37]
After #32, we have a few issues left related to the ticket form widget:

* [x] Remove giant visual gap between ticket form and headline (this is kind of okay after the background of the widget was changed to `#EEE`)
* [ ] Handle bank transfer information?
* [ ] "Send me DjangoCon EU 2019 updates and special offers" - we can remove this. Instead, we send all guest email addresses an invite to the member site once paid.
* [ ] On Step 2 of ordering, the widget becomes 1453 px high, leaving lots of empty space at the bottom (Firefox)
* [ ] Mobile display issues

![screenshot_20181231-165228](https://user-images.githubusercontent.com/374612/50563407-d4af1480-0d1c-11e9-9892-89f8e275560c.png)

**Comment by sodevious** [comment]
The step 2 form issue may be an issue with ticketbutler as it's an iframe... would have to dig deeper.

**Comment by benjaoming** [comment]
It is indeed, all of these items are related to the ticket widget specifically :)

**Comment by benjaoming** [comment]
A lot of this is fixed now, but we should add general "pay via bank wire" instruction still. They are NOT to be communicated without caution though, because we need to anticipate over-selling close to selling out.. preferring to ask people to send an email firstly with their intention, get a ticket reserved, initiate the wire, then get a ticket coupon once the wire is confirmed.
