### ISSUE TITLE
Email ticket system

### ISSUE THREAD

**Issue by benjaoming** [djangocon/2019.djangocon.eu#55]
We decided that we'd need an email ticket system, and we most likely will experience this need quite soon.

Should we implement django-helpdesk in the main Django project? Should we run a separate service?

**Comment by hellvix** [comment]
Anything that is simple to implement and that works. We might have tons of e-mails to answer and without proper management, we will have 2x more work to do.

**Comment by emilkjer** [comment]
There was a ticketing system used last year. Tobias was involved with the setup as far as I recall :) 


----------------------------------------
Emil Brøgger Kjer
Esplanaden 7, Copenhagen K - Denmark
T: (+45) 42 92 96 66

**Comment by benjaoming** [comment]
Word from Heidelberg was that they used [Zammad](https://zammad.org/)

**Comment by benjaoming** [comment]
This is done!
