### ISSUE TITLE
CSS filter on image is slow, maybe apply effect directly in photo?

### ISSUE THREAD

**Issue by benjaoming** [djangocon/2019.djangocon.eu#65]
CC: @sodevious

**Comment by sodevious** [comment]
@benjaoming On which images? There aren't any CSS filters, but maybe the images are too large or something...

**Comment by benjaoming** [comment]
Aaaah, I thought it was a filter. Sorry, yesterday the header background was very jumpy in the way it loaded, took a second or two before it showed up.

```
.header-hero::before {

    background: #00204a;
    content: "";
    position: absolute;
    opacity: .85;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;

}
```
