### ISSUE TITLE
Submenu visibility

### ISSUE THREAD

**Issue by hellvix** [djangocon/2019.djangocon.eu#76]
Is it possible to have a highlight for submenus? I think "Hospitality" and "Visa Information" are a bit hidden where they are. If you click on "Tickets" and start scrolling immediately, it might be easy to miss out the submenu.

**Comment by benjaoming** [comment]
I was thinking that they could have a solid background and white font color? Such that the whole menu bar becomes more profiled?

**Comment by benjaoming** [comment]
Kind of like this

![image](https://user-images.githubusercontent.com/374612/50964511-c9ec4080-14cf-11e9-9a61-98c9dcef6dc0.png)

Or this

![image](https://user-images.githubusercontent.com/374612/50965104-52b7ac00-14d1-11e9-89c8-689c5873a5e5.png)

**Comment by hellvix** [comment]
Yes. I like the first better. Matches the red I've seen in the hyperlink.

**Comment by sodevious** [comment]
i like the first one too
