### ISSUE TITLE
Sub menu is hard to grasp if there is only one item

### ISSUE THREAD

**Issue by benjaoming** [djangocon/2019.djangocon.eu#83]
I got a bit concerned when looking at a page with just one sub-page. Please feel free to close this if you disagree with this observation :)

Example:

![image](https://user-images.githubusercontent.com/374612/51001576-bde49b00-1530-11e9-8104-0c90dbd6a89e.png)

**Comment by lorinkoz** [comment]
Suggestion: when there is a submenu, add the landing page as an option too

**Comment by benjaoming** [comment]
That's a good idea. So in the example would be "Call for Participation: Speaker mentors" (and then "Call for Participation" highlighted as the selected item).

**Comment by lorinkoz** [comment]
May I take this one?

**Comment by lorinkoz** [comment]
Can we close here?

**Comment by benjaoming** [comment]
Yes, it looks good, thanks so much @lorinkoz :)
