### ISSUE TITLE
Fix facebook OG tags

### ISSUE THREAD

**Issue by sodevious** [djangocon/2019.djangocon.eu#99]
<img width="448" alt="screenshot 2019-01-15 at 14 06 07" src="https://user-images.githubusercontent.com/915966/51190824-5b4e1f00-18e3-11e9-9f62-e688e2351e08.png">

**Comment by benjaoming** [comment]
Could someone with a Facebook login go to the Facebook developer section where you can preview and invalidate cache and check if it works now?

**Comment by sodevious** [comment]
<img width="864" alt="screenshot 2019-01-16 15 44 51" src="https://user-images.githubusercontent.com/915966/51256537-e7c11600-19a5-11e9-8010-66c75bd6cc17.png">
